apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: default
spec:
  limits:
    - default:
        memory: 1Gi
        cpu: 1
      defaultRequest:
        memory: 512Mi
        cpu: 500m
      type: Container

